// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CopyCount
#pragma kernel CopyBuffer
#pragma kernel CopyIndirect
#pragma kernel CopyToStorage
#pragma kernel CopyDirectToStorage
#pragma kernel CopyFromStorage

StructuredBuffer<uint> source;
uint rOffset;

RWStructuredBuffer<uint> destination;
uint wOffset;

[numthreads(1,1,1)]
void CopyCount (uint3 id : SV_DispatchThreadID)
{
    destination[wOffset] = source[rOffset];
}

uint count;
uint stride;

[numthreads(256,1,1)]
void CopyBuffer (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= count * stride)
        return;
    destination[wOffset + id.x] = source[rOffset + id.x];
}

[numthreads(256,1,1)]
void CopyIndirect (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= source[count])
        return;
        
    for (uint i = id.x * stride; i < (id.x + 1) * stride; i++) {
        destination[wOffset + i] = source[rOffset + i];
    }
}

StructuredBuffer<uint2> _AddressDict;
uint addressIndex;
RWStructuredBuffer<uint> _DestMemory;
StructuredBuffer<uint> _SourceMemory;

[numthreads(256,1,1)]
void CopyToStorage (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= source[count])
        return;

    uint destBase = _AddressDict[addressIndex].x;
    for (uint i = id.x * stride; i < (id.x + 1) * stride; i++) {
        _DestMemory[destBase + i] = source[rOffset + i];
    }
}

[numthreads(256,1,1)]
void CopyDirectToStorage (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= count * stride)
        return;

    uint destBase = _AddressDict[addressIndex].x;
    _DestMemory[destBase + id.x] = source[rOffset + id.x];
}

[numthreads(256,1,1)]
void CopyFromStorage (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= source[count])
        return;

    uint srcBase = _AddressDict[addressIndex].x;
    for (uint i = id.x * stride; i < (id.x + 1) * stride; i++) {
        destination[wOffset + i] = _SourceMemory[srcBase + i];
    }
}
