#include "Assets/Resources/MapData/CCoordHash.hlsl"
#pragma kernel CSMain

RWStructuredBuffer<uint2> chunkAddressDict;
RWStructuredBuffer<uint2> nAddress;
int3 CCoord;
uint meshSkipInc;


[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint hash = HashCoord(CCoord);
    uint2 oldData = chunkAddressDict[hash];
    chunkAddressDict[hash] = uint2(nAddress[0].x, meshSkipInc);
    nAddress[0] = oldData;
}
