#include "Assets/Resources/Compute/MapData/CCoordHash.hlsl"
#pragma kernel CSMain

RWStructuredBuffer<uint2> chunkAddressDict;
RWStructuredBuffer<uint2> _AddressDict;
uint addressIndex;
int3 CCoord;
uint meshSkipInc;


[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint hash = HashCoord(CCoord);
    uint2 oldData = chunkAddressDict[hash]; 
    chunkAddressDict[hash] = uint2(_AddressDict[addressIndex].y, meshSkipInc);
    _AddressDict[addressIndex] = oldData;
}
