#pragma kernel CSMain

const static int numThreads = 8;

struct check{
    uint index;
    float3 position;
    uint value;
};


ConsumeStructuredBuffer<check> dataIN;
RWStructuredBuffer<check> dataOUT;
StructuredBuffer<uint> numPoints;

[numthreads(numThreads,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= numPoints[0])
        return;

    dataOUT[id.x] = dataIN.Consume();
}
