// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

StructuredBuffer<uint> _PrefixStart;
uint shaderIndex;
uint threadGroupSize;

RWStructuredBuffer<uint> indirectArgs;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint numThreads = ceil((float)(_PrefixStart[shaderIndex + 1] - _PrefixStart[shaderIndex]) / threadGroupSize);
    indirectArgs[0] = numThreads;
}
