// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Underground

#include "/Includes/PerlinNoiseGenerator.compute"

const static int numThreads = 8;
uint numPoints;
StructuredBuffer<float3> CheckPoints;
RWStructuredBuffer<float> Results;

[numthreads(numThreads,1,1)]
void Underground (uint3 id : SV_DispatchThreadID)//
{
    if(id.x > numPoints)
        return;

    Results[id.x] = GetNoise(CheckPoints[id.x]);
}
