name: Unity Activation

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request Unity activation file
    runs-on: ubuntu-latest

    steps:
      - name: Request manual Unity activation file
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.2.14f1

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.2.14f1.alf
          path: Unity_v6000.2.14f1.alf
